cmake_minimum_required(VERSION 3.13)
include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(efspike C CXX ASM)
pico_sdk_init()
foreach(t blink busy)
  add_executable(${t} ${t}.c)
  target_link_libraries(${t} pico_stdlib hardware_adc hardware_pwm hardware_i2c hardware_spi)
  pico_enable_stdio_uart(${t} 1)
  pico_enable_stdio_usb(${t} 0)
endforeach()
